[package]
name = "iguazu-egui"
authors.workspace = true
description = "Iguazu UI components with egui"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
iguazu.workspace = true
num-rational.workspace = true
num-traits.workspace = true
indexmap.workspace = true
hashbrown.workspace = true
egui.workspace = true
serde = "1.0.160"
time = { version = "0.3.20", features = ["serde", "macros", "formatting"] }
by_address = "1.1.0"
