[package]
name = "iguazu-egui"
authors.workspace = true
description = "Iguazu UI components with egui"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
iguazu.workspace = true
egui.workspace = true
log.workspace = true
ecow.workspace = true
async-executor.workspace = true
egui_table = "0.10.0"
itertools = "0.15.0"
