[package]
name = "iguazu-viewer"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
iguazu = { workspace = true, features = ["clap", "web"] }
iguazu-egui.workspace = true
egui.workspace = true
eframe = { version = "0.33.0", default-features = false, features = ["accesskit", "default_fonts", "wgpu", "wayland"] }
futures-lite = "2.6.0"
clap = { workspace = true, features = ["derive"] }
async-executor.workspace = true
wgpu = { version = "27", features = ["webgl"] }
rfd = { version = "0.17.2", features = ["file-handle-inner"] }
url = "2.5.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3.16"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"
log = "0.4.27"
send_wrapper = { version = "0.6.0", features = ["futures"] }
