use std::{env, fs, path::Path};

use iguazu_cli::Cli;

/// Snapshot test ensuring the CLI markdown documentation is up to date.
#[test]
fn markdown_docs_snapshot() -> Result<(), ()> {
    let generated = clap_markdown::help_markdown::<Cli>();
    let generated = format!("<!-- Generated by iguazu-cli/tests/markdown_docs_snapshot.rs. Edit the source text in the docstrings -->\n\n{generated}");

    let snapshot_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/cli.md");

    let snapshot = match fs::read_to_string(&snapshot_path) {
        Ok(contents) => contents,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => "".into(),
        Err(err) => panic!("failed to read {}: {err}", snapshot_path.display()),
    };

    if snapshot == generated {
        eprintln!("CLI docs up to date");
        return Ok(());
    } else if env::var("UPDATE_CLI_DOCS").is_ok() {
        fs::write(&snapshot_path, &generated).unwrap();
        eprintln!("CLI docs written to {}", snapshot_path.display());
        return Ok(());
    } else {
        eprintln!("CLI docs in {} out of date. Run with `UPDATE_CLI_DOCS=1` to update", snapshot_path.display());
        return Err(());
    }
}
